language: node_js
node_js:
  - "11.0"
branches:
  only:
    - master
before-script: 
  - npm install -g firebase-tools
script:
  - npm install
  - npm run build
  - firebase deploy --only hosting --project portfolio-ec01a --non-interactive --token=$FIREBASE_TOKEN -m "Github deploy"